Group commands in functions
stackbuilders/haskell-faas-template pull request #9
Opened 2022-06-02 17:06 UTC by LuisCoralesM

2022-06-02 19:13 UTC, dbalseiro requested changes

2022-06-02 19:13 UTC, dbalseiro commented on provisioner.sh
> +  # Install microk8s
While it's good to document the code, this comment in particular doesn't add much value. In fact is a direct transcription of the function name.

https://www.freecodecamp.org/news/code-comments-the-good-the-bad-and-the-ugly-be9cc65fbf83/

2022-06-02 19:13 UTC, dbalseiro commented on provisioner.sh
> +  # Start the service with all modules enabled
for instances, this comment is ok

2022-06-02 19:13 UTC, dbalseiro commented on provisioner.sh
> +  # Add all the necessary packages and permissions to use microk8s
A better comment would have been something explaining **why** do we need those permissions or what happens if we don't have the correct permissions

2022-06-02 19:13 UTC, dbalseiro commented on provisioner.sh
> +  # Install openfaas-cli
same as the first comment.. I would've called the function `install_openfaas_cli` if that's what it does

2022-06-02 19:13 UTC, dbalseiro commented on provisioner.sh
> +}
this one seem closely related to the next one... it's probably better to merge them together or make one call the other

This has to do with [cohesion](https://thevaluable.dev/cohesion-coupling-guide-examples/)

2022-06-02 21:36 UTC, LuisCoralesM commented
I deleted the comments related to the functions names and improved the explanation on the requested ones

2022-06-06 14:34 UTC, dbalseiro approved these changes
LGTM

2022-06-06 14:48 UTC, merged